image: Visual Studio 2019
configuration: Release
skip_branch_with_pr: true
skip_commits:
  files:
    - ".github/*"
    - "Docs/*"
    - ".travis.yml"
    - ".gitignore"
    - "*.md"
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  MSYSTEM: MINGW64
  MSYS2_PATH_TYPE: inherit
  PKG_CONFIG_PATH: C:/msys64/mingw64/lib/pkgconfig

install:
  - set "PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%"
  - ps: (New-Object System.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/OpenVisualCloud/SVT-AV1-Resources/master/video.tar.gz', "$PWD\video.tar.gz")
  - tar xf video.tar.gz
  - pacman -Syyuu --ask=20 --noconfirm --noprogressbar --needed
  - pacman -Suu --ask=20 --noconfirm --noprogressbar --needed mingw-w64-x86_64-yasm mingw-w64-x86_64-ccache mingw-w64-x86_64-gcc pkg-config make
  - cmake -S . -B Build -G"Unix Makefiles" -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/msys64/mingw64 -DBUILD_SHARED_LIBS=off

build_script:
  - make -C Build -j install
  - pkg-config --debug --exists --print-errors SvtAv1Enc
  - git clone https://github.com/FFmpeg/FFmpeg.git --depth=1 --branch=master ffmpeg
  - cd ffmpeg
  - git apply --ignore-space-change --ignore-whitespace %APPVEYOR_BUILD_FOLDER%/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
  - ps: |
      $path = ([System.Environment]::GetEnvironmentVariable('PATH', 'Machine').Split(';') | Where-Object { $_ -notmatch 'Git' }) -join ';'
      [System.Environment]::SetEnvironmentVariable('PATH', $path, 'Machine')
  - bash -c './configure --arch=x86_64 --cc="ccache gcc" --cxx="ccache g++" --enable-libsvtav1 --enable-encoder=libsvt_av1 || { cat ffbuild/config.log; exit 1; }'
  - make -j 10
  - ffmpeg -i ../akiyo_cif.y4m -c:v libsvt_av1 akiyo.mp4
  - cd ..
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "master" -and $null -eq $env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT) { Push-AppveyorArtifact -FileName ffmpeg.exe $(Get-ChildItem "ffmpeg\ffmpeg.exe").FullName }

test_script:
  - Bin\%CONFIGURATION%\SvtAv1EncApp -enc-mode 0 -i akiyo_cif.y4m -n 3
  - Bin\%CONFIGURATION%\SvtAv1EncApp -enc-mode 8 -i akiyo_cif.y4m -n 150

cache:
  - 'C:\msys64\home\appveyor\.ccache'
  - 'C:\msys64\var\cache\pacman\pkg'
