name: Releases
on:
  release:
    published:

jobs:
  MSVC:
    runs-on: windows-2019
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: choco install -y nasm

      - name: Configure static SVT-AV1
        run: cmake -S . -B Build-static -G "Visual Studio 16 2019" -A x64 -DBUILD_SHARED_LIBS=OFF -DCMAKE_OUTPUT_DIRECTORY="${{ github.workspace }}/static"
      - name: Configure shared SVT-AV1
        run: cmake -S . -B Build-shared -G "Visual Studio 16 2019" -A x64 -DBUILD_SHARED_LIBS=ON -DCMAKE_OUTPUT_DIRECTORY="${{ github.workspace }}/shared"
      - name: Build static SVT-AV1
        run: cmake --build Build-static --parallel 4 --config Release
      - name: Build shared SVT-AV1
        run: cmake --build Build-shared --parallel 4 --config Release
      - name: Zip shared build
        run: 7z.exe a SvtAv1Enc-shared.zip ./shared/Release/SvtAv1Enc.dll ./shared/Release/SvtAv1Enc.lib ./shared/Release/SvtAv1EncApp.exe

      - name: Get Current Release
        id: get_release
        shell: bash
        run: echo "::set-output name=upload_url::$(curl -L https://api.github.com/repos/${{ github.repository }}/releases/tags/$(cut -d/ -f3 <<< ${{ github.ref }}) | jq -r ."upload_url")"

      - name: Upload static SvtAv1EncApp.exe
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: static/Release/SvtAv1EncApp.exe
          asset_name: SvtAv1EncApp.exe
          asset_content_type: application/vnd.microsoft.portable-executable
      - name: Upload static SvtAv1DecApp.exe
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: static/Release/SvtAv1DecApp.exe
          asset_name: SvtAv1DecApp.exe
          asset_content_type: application/vnd.microsoft.portable-executable
      - name: Upload static SvtAv1Enc.lib
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: static/Release/SvtAv1Enc.lib
          asset_name: SvtAv1Enc.lib
          asset_content_type: application/octet-stream

      - name: Upload SvtAv1Enc-shared.zip
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: SvtAv1Enc-shared.zip
          asset_name: SvtAv1Enc-shared.zip
          asset_content_type: application/zip
