name: Sanitizers
on:
  - push
  - pull_request
env:
  CC: clang
  CXX: clang++

jobs:
  sanitizers:
    name: Sanitizer
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        sanitizer: ['address', 'memory', 'thread']
        include:
          - sanitizer: address
            env:
              ASAN_OPTIONS: detect_leaks=1
              CFLAGS: -fsanitize=address
              CXXFLAGS: -fsanitize=address
              LDFLAGS: -fsanitize=address

          - sanitizer: memory
            env:
              CFLAGS: -fsanitize=memory -fno-omit-frame-pointer
              CXXFLAGS: -fsanitize=memory -fno-omit-frame-pointer
              LDFLAGS: -fsanitize=memory
            svt-args: '--asm 0'

          - sanitizer: thread
            env:
              CFLAGS: -fsanitize=thread
              CXXFLAGS: -fsanitize=thread
              LDFLAGS: -fsanitize=thread
    env:
        ${{ matrix.env }}

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yasm ninja-build

    - uses: actions/checkout@v2

    - name: Run CMake
      run: cmake -S . -B Build -G Ninja -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build Build

    - name: Fetch test videos
      run: |
        wget -nc https://raw.githubusercontent.com/OpenVisualCloud/SVT-AV1-Resources/master/video.tar.gz
        tar xzf video.tar.gz

    - name: Run Encoder
      run: ./Bin/Debug/SvtAv1EncApp -i Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m ${{ matrix.svt-args }} -n 120 --preset 8 -b output.ivf
